services:
  square-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.square-app.rule=Host(`squares.dnaracing.run`)"
      - "traefik.http.routers.square-app.entrypoints=websecure"
      - "traefik.http.routers.square-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.square-app.loadbalancer.server.port=3000"
      - "traefik.http.services.square-app.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.square-app.loadbalancer.healthcheck.interval=30s"
      # Rate limiting
      - "traefik.http.middlewares.square-ratelimit.ratelimit.burst=1000"
      - "traefik.http.middlewares.square-ratelimit.ratelimit.average=1000"
      - "traefik.http.routers.square-app.middlewares=square-ratelimit"
    networks:
      - traefik
    restart: unless-stopped

networks:
  # External Traefik network
  traefik:
    external: true
